# Generated by Django 5.1.2 on 2025-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_block", models.IntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=256)),
                ("signature", models.CharField(max_length=1024)),
                ("abi", models.JSONField()),
                ("topic_0", models.CharField(max_length=256)),
                ("contract_addresses", models.JSONField(null=True)),
                ("logs_count", models.PositiveBigIntegerField(default=0)),
                ("asset", models.CharField(max_length=256)),
                ("asset_source", models.CharField(max_length=256)),
                ("asset_source_name", models.CharField(max_length=256)),
                ("method_ids", models.JSONField(blank=True, null=True)),
            ],
            options={"unique_together": {("asset", "asset_source", "topic_0")}},
        )
    ]
