# Generated by Django 5.1.2 on 2025-06-30 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("oracles", "0002_priceevent_transmitters")]

    operations = [migrations.RemoveField(model_name="priceevent", name="method_ids")]
