# Generated by Django 5.1.2 on 2025-07-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("oracles", "0003_remove_priceevent_method_ids")]

    operations = [
        migrations.AddField(
            model_name="priceevent",
            name="last_inserted_block",
            field=models.IntegerField(default=0),
        )
    ]
