# Generated by Django 5.1.2 on 2025-10-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("oracles", "0004_priceevent_last_inserted_block")]

    operations = [
        migrations.AddField(
            model_name="priceevent",
            name="is_active",
            field=models.BooleanField(default=False),
        )
    ]
