# Generated by Django 5.1.2 on 2025-10-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("oracles", "0005_priceevent_is_active")]

    operations = [
        migrations.AddField(
            model_name="priceevent",
            name="authorized_senders",
            field=models.JSONField(blank=True, null=True),
        )
    ]
