services:
    postgres:
        image: postgres:14
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres # Make sure to set this
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            retries: 15
            start_period: 2s
        volumes:
            - postgres_data:/var/lib/postgresql/data
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 1000M

    redis:
        image: redis:7.0
        ports:
            - 6379:6379
        healthcheck:
            test: ["CMD-SHELL", "redis-cli --raw ping"]
            retries: 15
            start_period: 2s
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M

    clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
            - 8123:8123 # HTTP interface
            - 9000:9000 # Native interface
        environment:
            CLICKHOUSE_USER: clickhouse-user
            CLICKHOUSE_PASSWORD: clickhouse-password
        volumes:
            - clickhouse_data:/var/lib/clickhouse
            - clickhouse_logs:/var/log/clickhouse-server
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:8123/ping",
                ]
            retries: 15
            start_period: 2s
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 4000M

volumes:
    postgres_data:
        driver: local
    clickhouse_data:
        driver: local
    clickhouse_logs:
        driver: local
