databases:
  - name: postgressql
    databaseName: postgressql_nalh
    user: postgressql_nalh_user
    plan: pro-8gb
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"
    diskSizeGB: 20
services:
  - type: worker
    name: websocket-transactions-infura
    runtime: docker
    repo: https://github.com/aknirmal90/liquidations_v2
    plan: standard
    envVars:
      - key: DOPPLER_TOKEN
        sync: false
    region: oregon
    dockerCommand: /start-websocket-transactions arbitrum infura
    dockerContext: .
    dockerfilePath: ./Dockerfile
  - type: web
    name: django
    runtime: docker
    repo: https://github.com/aknirmal90/liquidations_v2
    plan: starter
    envVars:
      - key: DOPPLER_TOKEN
        sync: false
    region: oregon
    healthCheckPath: /health/
    dockerCommand: /start-webserver
    dockerContext: .
    dockerfilePath: ./Dockerfile
  - type: worker
    name: celery-beat
    runtime: docker
    repo: https://github.com/aknirmal90/liquidations_v2
    plan: starter
    envVars:
      - key: DOPPLER_TOKEN
        sync: false
    region: oregon
    dockerCommand: /start-celery-beat
    dockerContext: .
    dockerfilePath: ./Dockerfile
  - type: worker
    name: celery-default
    runtime: docker
    repo: https://github.com/aknirmal90/liquidations_v2
    plan: standard
    envVars:
      - key: DOPPLER_TOKEN
        sync: false
    region: oregon
    dockerCommand: /start-celery-default
    dockerContext: .
    dockerfilePath: ./Dockerfile
  - type: redis
    name: redis
    plan: standard
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
version: "1"
