events:

  - name: "BridgeRelayed"
    index: "args.transactionId"
    direction: "receive"

  - name: "BridgeRequested"
    index: "args.transactionId"
    direction: "send"

networks:
  - network: "ethereum"
