events:
  - CollateralConfigurationChanged
  - ReserveInitialized
  - AssetSourceUpdated
  - EModeAssetCategoryChanged
  - AssetCollateralInEModeChanged
  - AssetBorrowableInEModeChanged
  - EModeCategoryAdded
  - PriceCapUpdated
  - CapParametersUpdated
  - LiquidationCall
  - Mint
  - Burn
  - BalanceTransfer
  - ReserveUsedAsCollateralDisabled
  - ReserveUsedAsCollateralEnabled
  - UserEModeSet

contract_addresses:
  - "0x8145edddf43f50276641b55bd3ad95944510021e"
  - "0xb56c2F0B653B2e0b10C9b928C8580Ac5Df02C7C7"
  - "0x794a61358D6845594F94dc1DB02A252b5b4814aD"
