events:
  - CollateralConfigurationChanged
  - ReserveInitialized
  - AssetSourceUpdated
  - EModeAssetCategoryChanged
  - EModeCategoryAdded
  - PriceCapUpdated
  - CapParametersUpdated
  - LiquidationCall
  - Mint
  - Burn
  - BalanceTransfer
  - ReserveUsedAsCollateralDisabled
  - ReserveUsedAsCollateralEnabled
  - UserEModeSet

contract_addresses:
  - "0x87870bca3f3fd6335c3f4ce8392d69350b4fa4e2"
  - "0x54586be62e3c3580375ae3723c145253060ca0c2"
  - "0x64b761d848206f447fe2dd461b0c635ec39ebb27"
