# Generated by Django 5.1.2 on 2024-12-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("string", "String"),
                        ],
                        default="string",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
                "ordering": ["key"],
            },
        )
    ]
