# Generated by Django 5.1.2 on 2024-12-14 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0001_initial")]

    operations = [migrations.RemoveField(model_name="protocol", name="type")]
