# Generated by Django 5.1.2 on 2025-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("blockchains", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="logs_count",
            field=models.PositiveBigIntegerField(default=0),
        )
    ]
