# Generated by Django 5.1.2 on 2024-12-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0003_event_converter_name_event_model_class_and_more")
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="event_abi", new_name="abi"
        ),
        migrations.RenameField(
            model_name="event", old_name="event_name", new_name="name"
        ),
        migrations.RenameField(
            model_name="event", old_name="event_signature", new_name="signature"
        ),
        migrations.RenameField(
            model_name="event", old_name="event_topic_0", new_name="topic_0"
        ),
        migrations.RemoveField(model_name="event", name="model_primary_key"),
    ]
