# Generated by Django 5.1.2 on 2024-12-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0005_remove_event_converter_name")]

    operations = [migrations.RemoveField(model_name="network", name="rpc_adapter_path")]
