# Generated by Django 5.1.2 on 2024-12-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0006_remove_network_rpc_adapter_path")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="contract_addresses",
            field=models.JSONField(null=True),
        )
    ]
