# Generated by Django 5.1.2 on 2024-12-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0008_delete_token")]

    operations = [
        migrations.AddField(
            model_name="network",
            name="wss",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="network",
            name="rpc",
            field=models.URLField(blank=True, null=True),
        ),
    ]
