# Generated by Django 5.1.2 on 2024-12-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0009_network_wss_alter_network_rpc")]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="wss",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
