# Generated by Django 5.1.2 on 2024-12-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0012_network_wss_tatum_network_wss_tenderly")]

    operations = [migrations.RemoveField(model_name="network", name="wss_tatum")]
