# Generated by Django 5.1.2 on 2025-01-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0013_remove_network_wss_tatum")]

    operations = [
        migrations.AddField(
            model_name="network",
            name="wss_chainstack",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
