# Generated by Django 5.1.2 on 2025-01-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0014_network_wss_chainstack")]

    operations = [
        migrations.AddField(
            model_name="network",
            name="chain_id",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
