# Generated by Django 5.1.2 on 2025-01-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0015_network_chain_id")]

    operations = [
        migrations.RenameField(
            model_name="network",
            old_name="wss_alchemy",
            new_name="wss_sequencer_virginia",
        ),
        migrations.RemoveField(model_name="network", name="wss_chainstack"),
        migrations.RemoveField(model_name="network", name="wss_nodereal"),
        migrations.RemoveField(model_name="network", name="wss_quicknode"),
        migrations.RemoveField(model_name="network", name="wss_tenderly"),
    ]
