# Generated by Django 5.1.2 on 2025-01-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "blockchains",
            "0016_rename_wss_alchemy_network_wss_sequencer_virginia_and_more",
        )
    ]

    operations = [
        migrations.RenameField(
            model_name="network",
            old_name="wss_sequencer_virginia",
            new_name="wss_sequencer_oregon",
        )
    ]
