# Generated by Django 5.1.2 on 2025-01-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blockchains", "0018_approximateblocktimestamp")]

    operations = [migrations.DeleteModel(name="Contract")]
