from decimal import Decimal

from decouple import config

PROTOCOL_NAME = config("PROTOCOL_NAME")

NETWORK_NAME = config("NETWORK_NAME")

PROTOCOL_CONFIG_PATH = f"{PROTOCOL_NAME}/config.yaml"

PROTOCOL_ABI_PATH = f"{PROTOCOL_NAME}/abi.json"

PRICES_ABI_PATH = "oracles/abi.json"

EVM_NULL_ADDRESS = "0x0000000000000000000000000000000000000000"

BALANCES_AMOUNT_ERROR_THRESHOLD_PCT = Decimal("0.000001")

BALANCES_AMOUNT_ERROR_THRESHOLD_VALUE = Decimal("10.0")

NETWORK_REFERENCE_BLOCK = config("NETWORK_REFERENCE_BLOCK", cast=int)

NETWORK_REFERENCE_TIMESTAMP = config("NETWORK_REFERENCE_TIMESTAMP", cast=int)

NETWORK_BLOCK_TIME = config("NETWORK_BLOCK_TIME", cast=int)

NETWORK_RPC = config("NETWORK_RPC")
