# Generated by Django 5.1.2 on 2024-12-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0005_alter_asset_decimals_alter_asset_num_decimals")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="price_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("constant", "Constant"),
                    ("aggregator", "Aggregator"),
                    ("max_capped", "Max Capped"),
                    ("ratio", "Ratio"),
                ],
                max_length=255,
                null=True,
            ),
        )
    ]
