# Generated by Django 5.1.2 on 2024-12-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0006_asset_price_type")]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="denominator",
            field=models.DecimalField(decimal_places=0, max_digits=36),
        ),
        migrations.AlterField(
            model_name="asset",
            name="numerator",
            field=models.DecimalField(decimal_places=0, max_digits=36),
        ),
        migrations.AlterField(
            model_name="asset",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=36, max_digits=72, null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="priceA",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=72, null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="priceB",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=72, null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="price_in_usdt",
            field=models.DecimalField(
                blank=True, decimal_places=36, max_digits=72, null=True
            ),
        ),
    ]
