# Generated by Django 5.1.2 on 2024-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0008_alter_asset_denominator_alter_asset_numerator")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="borrowable_in_isolation_mode",
            field=models.BooleanField(default=False),
        )
    ]
