# Generated by Django 5.1.2 on 2024-12-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0009_asset_borrowable_in_isolation_mode")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_reserve_paused",
            field=models.BooleanField(default=False),
        )
    ]
