# Generated by Django 5.1.2 on 2024-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0010_asset_is_reserve_paused")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="reserve_factor",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="reserve_is_borrow_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="reserve_is_flash_loan_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="reserve_is_frozen",
            field=models.BooleanField(default=False),
        ),
    ]
