# Generated by Django 5.1.2 on 2024-12-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0012_asset_emode_is_borrowable_asset_emode_is_collateral")
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="epoch_and_roundA",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="epoch_and_roundB",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="transmittersA",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="transmittersB",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
