# Generated by Django 5.1.2 on 2024-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0013_asset_epoch_and_rounda_asset_epoch_and_roundb_and_more")
    ]

    operations = [
        migrations.RenameField(
            model_name="asset", old_name="epoch_and_roundA", new_name="updated_at_db_A"
        ),
        migrations.RenameField(
            model_name="asset", old_name="epoch_and_roundB", new_name="updated_at_db_B"
        ),
        migrations.RemoveField(model_name="asset", name="transmittersA"),
        migrations.RemoveField(model_name="asset", name="transmittersB"),
        migrations.AddField(
            model_name="asset",
            name="updated_at_onchainA",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="updated_at_onchainB",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
