# Generated by Django 5.1.2 on 2024-12-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0015_assetpricelog"),
        ("blockchains", "0010_alter_network_wss"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assetpricelog", name="aave_assetp_asset_a_9e966b_idx"
        ),
        migrations.RenameField(
            model_name="assetpricelog",
            old_name="asset_address",
            new_name="aggregator_address",
        ),
        migrations.RemoveField(model_name="assetpricelog", name="protocol"),
        migrations.AddIndex(
            model_name="assetpricelog",
            index=models.Index(
                fields=["aggregator_address", "network"],
                name="aave_assetp_aggrega_e5e60a_idx",
            ),
        ),
    ]
