# Generated by Django 5.1.2 on 2024-12-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0016_remove_assetpricelog_aave_assetp_asset_a_9e966b_idx_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="assetpricelog",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=72, null=True
            ),
        )
    ]
