# Generated by Django 5.1.2 on 2024-12-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0017_alter_assetpricelog_price")]

    operations = [
        migrations.AddField(
            model_name="assetpricelog",
            name="round_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
