# Generated by Django 5.1.2 on 2024-12-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0020_assetpricelog_provider")]

    operations = [
        migrations.RenameField(
            model_name="asset", old_name="numerator", new_name="decimals_price"
        ),
        migrations.RenameField(
            model_name="asset", old_name="denominator", new_name="max_cap"
        ),
        migrations.AlterField(
            model_name="asset",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=72, null=True
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="price_in_usdt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=72, null=True
            ),
        ),
    ]
