# Generated by Django 5.1.2 on 2025-01-01 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0022_alter_asset_decimals_price_alter_asset_max_cap"),
        ("blockchains", "0014_network_wss_chainstack"),
    ]

    operations = [
        migrations.CreateModel(
            name="AaveLiquidationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=42)),
                (
                    "debt_to_cover",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=72, null=True
                    ),
                ),
                (
                    "debt_to_cover_in_usd",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=72, null=True
                    ),
                ),
                (
                    "liquidated_collateral_amount",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=72, null=True
                    ),
                ),
                (
                    "liquidated_collateral_amount_in_usd",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=72, null=True
                    ),
                ),
                ("liquidator", models.CharField(max_length=42)),
                ("block_height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "transaction_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                (
                    "transaction_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("onchain_created_at", models.DateTimeField(blank=True, null=True)),
                ("onchain_received_at", models.DateTimeField(blank=True, null=True)),
                ("db_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collateral_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collateral_liquidations",
                        to="aave.asset",
                    ),
                ),
                (
                    "debt_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debt_liquidations",
                        to="aave.asset",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blockchains.network",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blockchains.protocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aave Liquidation Log",
                "verbose_name_plural": "Aave Liquidation Logs",
                "indexes": [
                    models.Index(
                        fields=["network", "protocol", "user"],
                        name="aave_aaveli_network_925b47_idx",
                    )
                ],
            },
        )
    ]
