# Generated by Django 5.1.2 on 2025-01-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0023_aaveliquidationlog")]

    operations = [
        migrations.AlterField(
            model_name="aaveliquidationlog",
            name="debt_to_cover_in_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=70, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aaveliquidationlog",
            name="liquidated_collateral_amount_in_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=70, null=True
            ),
        ),
    ]
