# Generated by Django 5.1.2 on 2025-01-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0024_alter_aaveliquidationlog_debt_to_cover_in_usd_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="aaveliquidationlog",
            name="health_factor_before_one_blocks",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="aaveliquidationlog",
            name="health_factor_before_three_blocks",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="aaveliquidationlog",
            name="health_factor_before_two_blocks",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="aaveliquidationlog",
            name="health_factor_before_tx",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=8, null=True
            ),
        ),
    ]
