# Generated by Django 5.1.2 on 2025-01-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0025_aaveliquidationlog_health_factor_before_one_blocks_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="aaveliquidationlog",
            name="health_factor_before_tx_before_zero_blocks",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aaveliquidationlog",
            name="health_factor_before_one_blocks",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aaveliquidationlog",
            name="health_factor_before_three_blocks",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aaveliquidationlog",
            name="health_factor_before_two_blocks",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aaveliquidationlog",
            name="health_factor_before_tx",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=19, null=True
            ),
        ),
    ]
