# Generated by Django 5.1.2 on 2025-01-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "aave",
            "0026_aaveliquidationlog_health_factor_before_tx_before_zero_blocks_and_more",
        )
    ]

    operations = [
        migrations.RenameField(
            model_name="aaveliquidationlog",
            old_name="health_factor_before_tx_before_zero_blocks",
            new_name="health_factor_before_zero_blocks",
        )
    ]
