# Generated by Django 5.1.2 on 2025-01-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aave",
            "0027_rename_health_factor_before_tx_before_zero_blocks_aaveliquidationlog_health_factor_before_zero_block",
        )
    ]

    operations = [
        migrations.RemoveField(model_name="asset", name="updated_at_block_heightA"),
        migrations.RemoveField(model_name="asset", name="updated_at_block_heightB"),
        migrations.RemoveField(model_name="asset", name="updated_at_db_A"),
        migrations.RemoveField(model_name="asset", name="updated_at_db_B"),
        migrations.RemoveField(model_name="asset", name="updated_at_onchainA"),
        migrations.RemoveField(model_name="asset", name="updated_at_onchainB"),
        migrations.AddField(
            model_name="assetpricelog",
            name="transaction_hash",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
