# Generated by Django 5.1.2 on 2025-01-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0029_alter_assetpricelog_onchain_created_at")]

    operations = [
        migrations.AddField(
            model_name="assetpricelog",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
