# Generated by Django 5.1.2 on 2025-01-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0030_assetpricelog_processed_at"),
        (
            "blockchains",
            "0017_rename_wss_sequencer_virginia_network_wss_sequencer_oregon",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AaveBalanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=42)),
                (
                    "collateral_liquidity_index",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=72, null=True
                    ),
                ),
                (
                    "collateral_amount",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=72, null=True
                    ),
                ),
                ("collateral_is_enabled", models.BooleanField(default=False)),
                (
                    "borrow_liquidity_index",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=72, null=True
                    ),
                ),
                (
                    "borrow_amount",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=72, null=True
                    ),
                ),
                ("borrow_is_enabled", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="aave.asset"
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blockchains.network",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blockchains.protocol",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["network", "protocol", "address", "asset"],
                        name="aave_aaveba_network_b1bc55_idx",
                    )
                ],
                "unique_together": {("network", "protocol", "address", "asset")},
            },
        )
    ]
