# Generated by Django 5.1.2 on 2025-01-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0031_aavebalancelog")]

    operations = [
        migrations.CreateModel(
            name="AaveBurnEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_address", models.CharField(db_index=True, max_length=42)),
                ("target", models.CharField(db_index=True, max_length=42)),
                ("value", models.DecimalField(decimal_places=18, max_digits=72)),
                (
                    "balance_increase",
                    models.DecimalField(decimal_places=18, max_digits=72),
                ),
                ("index", models.DecimalField(decimal_places=18, max_digits=72)),
                ("block_height", models.PositiveBigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("transaction_index", models.PositiveIntegerField()),
                ("log_index", models.PositiveIntegerField()),
                (
                    "balance_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aave.aavebalancelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aave Burn Event",
                "verbose_name_plural": "Aave Burn Events",
            },
        ),
        migrations.CreateModel(
            name="AaveMintEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caller", models.CharField(db_index=True, max_length=42)),
                ("on_behalf_of", models.CharField(db_index=True, max_length=42)),
                ("value", models.DecimalField(decimal_places=18, max_digits=72)),
                (
                    "balance_increase",
                    models.DecimalField(decimal_places=18, max_digits=72),
                ),
                ("index", models.DecimalField(decimal_places=18, max_digits=72)),
                ("block_height", models.PositiveBigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("transaction_index", models.PositiveIntegerField()),
                ("log_index", models.PositiveIntegerField()),
                (
                    "balance_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aave.aavebalancelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aave Mint Event",
                "verbose_name_plural": "Aave Mint Events",
            },
        ),
        migrations.CreateModel(
            name="AaveTransferEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_address", models.CharField(db_index=True, max_length=42)),
                ("to_address", models.CharField(db_index=True, max_length=42)),
                ("value", models.DecimalField(decimal_places=18, max_digits=72)),
                ("block_height", models.PositiveBigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("transaction_index", models.PositiveIntegerField()),
                ("log_index", models.PositiveIntegerField()),
                (
                    "balance_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aave.aavebalancelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aave Transfer Event",
                "verbose_name_plural": "Aave Transfer Events",
            },
        ),
    ]
