# Generated by Django 5.1.2 on 2025-01-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("aave", "0032_aaveburnevent_aavemintevent_aavetransferevent")]

    operations = [
        migrations.AlterUniqueTogether(
            name="aaveburnevent",
            unique_together={
                ("transaction_hash", "block_height", "log_index", "balance_log")
            },
        ),
        migrations.AlterUniqueTogether(
            name="aavemintevent",
            unique_together={
                ("transaction_hash", "block_height", "log_index", "balance_log")
            },
        ),
        migrations.AlterUniqueTogether(
            name="aavetransferevent",
            unique_together={
                ("transaction_hash", "block_height", "log_index", "balance_log")
            },
        ),
    ]
