# Generated by Django 5.1.2 on 2025-01-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0033_alter_aaveburnevent_unique_together_and_more")]

    operations = [
        migrations.RenameField(
            model_name="aavebalancelog",
            old_name="collateral_liquidity_index",
            new_name="last_updated_liquidity_index",
        ),
        migrations.RemoveField(
            model_name="aavebalancelog", name="borrow_liquidity_index"
        ),
        migrations.AddField(
            model_name="asset",
            name="liquidity_index",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=72, null=True
            ),
        ),
    ]
