# Generated by Django 5.1.2 on 2025-01-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aave",
            "0034_rename_collateral_liquidity_index_aavebalancelog_last_updated_liquidity_index_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="aavebalancelog",
            name="collateral_amount_live",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=72, null=True
            ),
        )
    ]
