# Generated by Django 5.1.2 on 2025-01-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0035_aavebalancelog_collateral_amount_live"),
        (
            "blockchains",
            "0017_rename_wss_sequencer_virginia_network_wss_sequencer_oregon",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aavebalancelog",
            index=models.Index(
                fields=["network", "protocol", "asset"],
                name="aave_aaveba_network_51c4b4_idx",
            ),
        )
    ]
