# Generated by Django 5.1.2 on 2025-01-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0036_aavebalancelog_aave_aaveba_network_51c4b4_idx")]

    operations = [
        migrations.AddField(
            model_name="aavebalancelog",
            name="collateral_amount_live_is_verified",
            field=models.BooleanField(blank=True, default=None, null=True),
        )
    ]
