# Generated by Django 5.1.2 on 2025-01-05 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0037_aavebalancelog_collateral_amount_live_is_verified")]

    operations = [
        migrations.CreateModel(
            name="AaveSupplyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(db_index=True, max_length=42)),
                ("on_behalf_of", models.CharField(db_index=True, max_length=42)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=72)),
                ("referral_code", models.PositiveSmallIntegerField()),
                ("block_height", models.PositiveBigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("transaction_index", models.PositiveIntegerField()),
                ("log_index", models.PositiveIntegerField()),
                (
                    "balance_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aave.aavebalancelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aave Supply Event",
                "verbose_name_plural": "Aave Supply Events",
                "unique_together": {
                    ("transaction_hash", "block_height", "log_index", "balance_log")
                },
            },
        ),
        migrations.CreateModel(
            name="AaveWithdrawEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(db_index=True, max_length=42)),
                ("to_address", models.CharField(db_index=True, max_length=42)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=72)),
                ("block_height", models.PositiveBigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("transaction_index", models.PositiveIntegerField()),
                ("log_index", models.PositiveIntegerField()),
                (
                    "balance_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aave.aavebalancelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aave Withdraw Event",
                "verbose_name_plural": "Aave Withdraw Events",
                "unique_together": {
                    ("transaction_hash", "block_height", "log_index", "balance_log")
                },
            },
        ),
    ]
