# Generated by Django 5.1.2 on 2025-01-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0038_aavesupplyevent_aavewithdrawevent")]

    operations = [
        migrations.RemoveField(
            model_name="asset", name="interest_rate_strategy_address"
        ),
        migrations.AddField(
            model_name="asset",
            name="reserve_is_collateral_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
