# Generated by Django 5.1.2 on 2025-01-06 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0041_alter_aaveburnevent_balance_log_and_more"),
        (
            "blockchains",
            "0017_rename_wss_sequencer_virginia_network_wss_sequencer_oregon",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AaveDataQualityAnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("num_collateral_verified", models.PositiveIntegerField(default=0)),
                ("num_borrow_verified", models.PositiveIntegerField(default=0)),
                ("num_collateral_unverified", models.PositiveIntegerField(default=0)),
                ("num_borrow_unverified", models.PositiveIntegerField(default=0)),
                ("num_collateral_deleted", models.PositiveIntegerField(default=0)),
                ("num_borrow_deleted", models.PositiveIntegerField(default=0)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blockchains.network",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blockchains.protocol",
                    ),
                ),
            ],
        )
    ]
