# Generated by Django 5.1.2 on 2025-01-06 13:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aave",
            "0043_rename_last_updated_liquidity_index_aavebalancelog_last_updated_collateral_liquidity_index_and_more",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="aavebalancelog",
            name="borrow_amount",
            field=models.DecimalField(
                decimal_places=18, default=Decimal("0.0"), max_digits=72
            ),
        ),
        migrations.AlterField(
            model_name="aavebalancelog",
            name="borrow_amount_live",
            field=models.DecimalField(
                decimal_places=18, default=Decimal("0.0"), max_digits=72
            ),
        ),
        migrations.AlterField(
            model_name="aavebalancelog",
            name="collateral_amount",
            field=models.DecimalField(
                decimal_places=18, default=Decimal("0.0"), max_digits=72
            ),
        ),
        migrations.AlterField(
            model_name="aavebalancelog",
            name="collateral_amount_live",
            field=models.DecimalField(
                decimal_places=18, default=Decimal("0.0"), max_digits=72
            ),
        ),
    ]
