# Generated by Django 5.1.2 on 2025-01-06 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0044_alter_aavebalancelog_borrow_amount_and_more")]

    operations = [
        migrations.AlterField(
            model_name="aavebalancelog",
            name="last_updated_borrow_liquidity_index",
            field=models.DecimalField(
                decimal_places=0, default=Decimal("0.0"), max_digits=72
            ),
        ),
        migrations.AlterField(
            model_name="aavebalancelog",
            name="last_updated_collateral_liquidity_index",
            field=models.DecimalField(
                decimal_places=0, default=Decimal("0.0"), max_digits=72
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="borrow_liquidity_index",
            field=models.DecimalField(
                decimal_places=0, default=Decimal("0.0"), max_digits=72
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="collateral_liquidity_index",
            field=models.DecimalField(
                decimal_places=0, default=Decimal("0.0"), max_digits=72
            ),
        ),
    ]
