# Generated by Django 5.1.2 on 2025-01-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aave",
            "0045_alter_aavebalancelog_last_updated_borrow_liquidity_index_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="aaveburnevent",
            name="type",
            field=models.CharField(
                choices=[("collateral", "Collateral"), ("borrow", "Borrow")],
                default="collateral",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="aavemintevent",
            name="type",
            field=models.CharField(
                choices=[("collateral", "Collateral"), ("borrow", "Borrow")],
                default="collateral",
                max_length=10,
            ),
        ),
    ]
