# Generated by Django 5.1.2 on 2025-01-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0046_aaveburnevent_type_aavemintevent_type")]

    operations = [
        migrations.CreateModel(
            name="AaveBorrowEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(db_index=True, max_length=42)),
                ("on_behalf_of", models.CharField(db_index=True, max_length=42)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=72)),
                ("interest_rate_mode", models.PositiveSmallIntegerField()),
                ("borrow_rate", models.DecimalField(decimal_places=18, max_digits=72)),
                ("referral_code", models.PositiveSmallIntegerField()),
                ("block_height", models.PositiveBigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("transaction_index", models.PositiveIntegerField()),
                ("log_index", models.PositiveIntegerField()),
                (
                    "balance_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aave.aavebalancelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aave Borrow Event",
                "verbose_name_plural": "Aave Borrow Events",
                "unique_together": {
                    ("transaction_hash", "block_height", "log_index", "balance_log")
                },
            },
        ),
        migrations.CreateModel(
            name="AaveLiquidationCallEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collateral_asset", models.CharField(db_index=True, max_length=42)),
                ("debt_asset", models.CharField(db_index=True, max_length=42)),
                ("user", models.CharField(db_index=True, max_length=42)),
                (
                    "debt_to_cover",
                    models.DecimalField(decimal_places=18, max_digits=72),
                ),
                (
                    "liquidated_collateral_amount",
                    models.DecimalField(decimal_places=18, max_digits=72),
                ),
                ("liquidator", models.CharField(db_index=True, max_length=42)),
                ("receive_a_token", models.BooleanField()),
                ("block_height", models.PositiveBigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("transaction_index", models.PositiveIntegerField()),
                ("log_index", models.PositiveIntegerField()),
                (
                    "balance_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aave.aavebalancelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aave Liquidation Call Event",
                "verbose_name_plural": "Aave Liquidation Call Events",
                "unique_together": {
                    ("transaction_hash", "block_height", "log_index", "balance_log")
                },
            },
        ),
        migrations.CreateModel(
            name="AaveRepayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(db_index=True, max_length=42)),
                ("repayer", models.CharField(db_index=True, max_length=42)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=72)),
                ("use_a_tokens", models.BooleanField()),
                ("block_height", models.PositiveBigIntegerField()),
                ("transaction_hash", models.CharField(max_length=66)),
                ("transaction_index", models.PositiveIntegerField()),
                ("log_index", models.PositiveIntegerField()),
                (
                    "balance_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aave.aavebalancelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aave Repay Event",
                "verbose_name_plural": "Aave Repay Events",
                "unique_together": {
                    ("transaction_hash", "block_height", "log_index", "balance_log")
                },
            },
        ),
    ]
