# Generated by Django 5.1.2 on 2025-01-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("aave", "0047_aaveborrowevent_aaveliquidationcallevent_and_more")]

    operations = [
        migrations.AlterUniqueTogether(
            name="aaveburnevent",
            unique_together={
                ("transaction_hash", "block_height", "log_index", "balance_log", "type")
            },
        ),
        migrations.AlterUniqueTogether(
            name="aavemintevent",
            unique_together={
                ("transaction_hash", "block_height", "log_index", "balance_log", "type")
            },
        ),
    ]
