# Generated by Django 5.1.2 on 2025-01-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0049_aavebalancelog_collateral_is_enabled_updated_at_block")
    ]

    operations = [
        migrations.AddField(
            model_name="aaveliquidationlog",
            name="block_datetime",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
