# Generated by Django 5.1.2 on 2025-01-15 09:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0051_aaveliquidationlog_profit_in_usd")]

    operations = [
        migrations.AddField(
            model_name="aavebalancelog",
            name="collateral_amount_live_with_reserve_threshold",
            field=models.DecimalField(
                decimal_places=18, default=Decimal("0.0"), max_digits=72
            ),
        ),
        migrations.AddField(
            model_name="aavebalancelog",
            name="emode_category",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavebalancelog",
            name="emode_category_updated_at_block",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavebalancelog",
            name="health_factor",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=21, null=True
            ),
        ),
    ]
