# Generated by Django 5.1.2 on 2025-01-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "aave",
            "0052_aavebalancelog_collateral_amount_live_with_reserve_threshold_and_more",
        )
    ]

    operations = [
        migrations.RenameField(
            model_name="aavebalancelog",
            old_name="collateral_amount_live_with_reserve_threshold",
            new_name="collateral_amount_live_with_liquidation_threshold",
        )
    ]
