# Generated by Django 5.1.2 on 2025-01-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'aave',
            '0053_rename_collateral_amount_live_with_reserve_threshold_aavebalancelog_collateral_amount_live_with_liqu'
        ),
        ('blockchains', '0018_approximateblocktimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AaveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('health_factor', models.DecimalField(blank=True, decimal_places=18, max_digits=21, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='aavebalancelog',
            name='aave_aaveba_network_b1bc55_idx',
        ),
        migrations.RemoveIndex(
            model_name='aavebalancelog',
            name='aave_aaveba_network_51c4b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='aaveliquidationlog',
            name='aave_aaveli_network_925b47_idx',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='price_in_usdt',
            new_name='price_in_nativeasset',
        ),
        migrations.AlterUniqueTogether(
            name='aavebalancelog',
            unique_together={('network', 'address', 'asset')},
        ),
        migrations.RemoveField(
            model_name='aavedataqualityanalyticsreport',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='aaveliquidationlog',
            name='protocol',
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('network', 'asset')},
        ),
        migrations.AddField(
            model_name='aavebalancelog',
            name='collateral_health_factor',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=72, null=True),
        ),
        migrations.AddField(
            model_name='aavebalancelog',
            name='price_in_nativeasset',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=72, null=True),
        ),
        migrations.AddIndex(
            model_name='aaveliquidationlog',
            index=models.Index(fields=['network', 'user'], name='aave_aaveli_network_6ba45f_idx'),
        ),
        migrations.AddField(
            model_name='aaveuser',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchains.network'),
        ),
        migrations.AddField(
            model_name='aavebalancelog',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT, to='aave.aaveuser'
            ),
        ),
        migrations.AddIndex(
            model_name='aavebalancelog',
            index=models.Index(fields=['network', 'address', 'asset'], name='aave_aaveba_network_fe5d15_idx'),
        ),
        migrations.RemoveField(
            model_name='aavebalancelog',
            name='health_factor',
        ),
        migrations.RemoveField(
            model_name='aavebalancelog',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='protocol',
        ),
    ]
