# Generated by Django 5.1.2 on 2025-01-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aave', '0054_aaveuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aavebalancelog',
            name='price_in_nativeasset',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=72, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price_in_nativeasset',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=72, null=True),
        ),
    ]
