# Generated by Django 5.1.2 on 2025-01-18 18:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aave', '0055_alter_aavebalancelog_price_in_nativeasset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aavebalancelog',
            name='collateral_health_factor',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.0'), max_digits=72),
        ),
    ]
