# Generated by Django 5.1.2 on 2025-01-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aave', '0056_alter_aavebalancelog_collateral_health_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='borrowable_in_isolation_mode',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='emode_is_borrowable',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='emode_is_collateral',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_reserve_paused',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='reserve_factor',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='reserve_is_borrow_enabled',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='reserve_is_collateral_enabled',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='reserve_is_flash_loan_enabled',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='reserve_is_frozen',
        ),
    ]
