# Generated by Django 5.1.2 on 2025-01-19 06:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aave', '0057_remove_asset_borrowable_in_isolation_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='num_decimals',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3),
        ),
    ]
