# Generated by Django 5.1.2 on 2025-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0059_alter_asset_symbol")]

    operations = [
        migrations.AddField(
            model_name="aavebalancelog",
            name="borrow_liquidity_index_verified",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="aavebalancelog",
            name="collateral_liquidity_index_verified",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
