# Generated by Django 5.1.2 on 2025-01-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0060_aavebalancelog_borrow_liquidity_index_verified_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_borrow_index_unverified",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_borrow_index_verified",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_collateral_index_unverified",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_collateral_index_verified",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
