# Generated by Django 5.1.2 on 2025-01-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aave",
            "0061_aavedataqualityanalyticsreport_num_borrow_index_unverified_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="aavetransferevent",
            name="index",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=72, null=True
            ),
        )
    ]
