# Generated by Django 5.1.2 on 2025-01-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aave", "0062_aavetransferevent_index")]

    operations = [
        migrations.AddField(
            model_name="aavebalancelog",
            name="is_collateral_enabled_verified",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="aavebalancelog",
            name="is_emode_verified",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="aavebalancelog",
            name="is_verified",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
