# Generated by Django 5.1.2 on 2025-01-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aave", "0063_aavebalancelog_is_collateral_enabled_verified_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_all_unverified",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_all_verified",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_collateral_enabled_unverified",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_collateral_enabled_verified",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_emode_unverified",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aavedataqualityanalyticsreport",
            name="num_emode_verified",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
