name: CI

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Doppler CLI
        run: |
          sudo sh -c "$(curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh)"

      - name: Run Tests with Docker Compose
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "docker-compose-circleci.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "webserver"
          test-command: "doppler run --command 'pytest -vv --cov --cov-report=xml:coverage.xml --junit-xml=junit/test-results.xml' "
        env:
          DOPPLER_TOKEN: ${{ vars.DOPPLER_TOKEN }}

      - name: Store Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            junit/test-results.xml
            coverage.xml

      - name: Store Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report
