name: CI

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Doppler CLI
        run: |
          sudo sh -c "$(curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh)"

      - name: Start Local Development Environment
        run: |
          docker compose up postgres redis -d --wait --wait-timeout 200
        env:
          DOPPLER_TOKEN: ${{ vars.DOPPLER_TOKEN }}

      - name: Run Tests
        run: |
          export DOPPLER_TOKEN=${{ vars.DOPPLER_TOKEN }}
          doppler run --command "pytest -v"
        env:
          DOPPLER_TOKEN: ${{ vars.DOPPLER_TOKEN }}
