name: CI

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: cimg/python:3.9

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Install Doppler CLI
          (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh

      - name: Run Tests with Coverage
        run: |
          # Start services and wait for readiness
          docker-compose -f docker-compose-circleci.yml up -d
          docker-compose -f docker-compose-circleci.yml run --rm web \
            pytest --junitxml=junit/test-results.xml \
                   --cov=app \
                   --cov-report=xml:coverage.xml \
                   --cov-report=html:coverage-report
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Store Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            junit/test-results.xml
            coverage.xml

      - name: Store Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report
