# Generated by Django 5.1.2 on 2025-07-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("balances", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="balanceevent",
            name="asset",
            field=models.CharField(max_length=256, null=True),
        )
    ]
