# Generated by Django 5.1.2 on 2025-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("balances", "0002_balanceevent_asset")]

    operations = [
        migrations.AddField(
            model_name="balanceevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("Collateral", "Collateral"),
                    ("StableDebt", "Stable Debt"),
                    ("VariableDebt", "Variable Debt"),
                ],
                max_length=256,
                null=True,
            ),
        )
    ]
