# Generated by Django 5.1.2 on 2025-10-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("balances", "0003_balanceevent_type")]

    operations = [
        migrations.AlterField(
            model_name="balanceevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("Collateral", "Collateral"),
                    ("VariableDebt", "Variable Debt"),
                ],
                max_length=256,
                null=True,
            ),
        )
    ]
